import { drizzle } from 'drizzle-orm/postgres-js';
import postgres from 'postgres';
import bcrypt from 'bcryptjs';
import { brands, models, adminUsers } from './schema';

const connectionString = process.env.DATABASE_URL!;
const client = postgres(connectionString);
const db = drizzle(client);

async function seed() {
  console.log('Seeding database...');

  // ─── Admin User ──────────────────────────────────────────────────────────

  const passwordHash = await bcrypt.hash('admin123', 12);

  await db.insert(adminUsers).values({
    email: 'admin@chinacars.global',
    passwordHash,
    name: 'Admin',
    role: 'admin',
  });

  console.log('Admin user created: admin@chinacars.global');

  // ─── Brands ──────────────────────────────────────────────────────────────

  const [byd, nio, xpeng, geely, greatWall] = await db
    .insert(brands)
    .values([
      {
        slug: 'byd',
        name: 'BYD',
        websiteUrl: 'https://www.byd.com',
        descriptionEn:
          'BYD (Build Your Dreams) is the world\'s largest electric vehicle manufacturer, founded in 1995 in Shenzhen, China. Originally a battery maker, BYD has grown into a global powerhouse offering a full range of electric and hybrid vehicles.',
        descriptionRo:
          'BYD (Build Your Dreams) este cel mai mare producator de vehicule electrice din lume, fondat in 1995 in Shenzhen, China. Initial un producator de baterii, BYD a crescut intr-o forta globala oferind o gama completa de vehicule electrice si hibride.',
        foundedYear: 1995,
        isPublished: true,
        sortOrder: 1,
      },
      {
        slug: 'nio',
        name: 'NIO',
        websiteUrl: 'https://www.nio.com',
        descriptionEn:
          'NIO is a premium smart electric vehicle company founded in 2014. Known for its innovative battery-swap technology and high-performance EVs, NIO is expanding rapidly across European markets.',
        descriptionRo:
          'NIO este o companie premium de vehicule electrice inteligente fondata in 2014. Cunoscuta pentru tehnologia inovatoare de schimb de baterie si EV-urile de inalta performanta, NIO se extinde rapid pe pietele europene.',
        foundedYear: 2014,
        isPublished: true,
        sortOrder: 2,
      },
      {
        slug: 'xpeng',
        name: 'XPeng',
        websiteUrl: 'https://www.xpeng.com',
        descriptionEn:
          'XPeng Motors is a leading Chinese smart EV company founded in 2014, focused on technology-driven electric vehicles with advanced autonomous driving capabilities.',
        descriptionRo:
          'XPeng Motors este o companie chineza de top de EV-uri inteligente fondata in 2014, concentrata pe vehicule electrice bazate pe tehnologie cu capabilitati avansate de conducere autonoma.',
        foundedYear: 2014,
        isPublished: true,
        sortOrder: 3,
      },
      {
        slug: 'geely',
        name: 'Geely',
        websiteUrl: 'https://www.geely.com',
        descriptionEn:
          'Geely Auto Group is one of China\'s largest privately-owned automotive manufacturers, founded in 1986. The parent company also owns Volvo Cars, Polestar, and Lotus.',
        descriptionRo:
          'Geely Auto Group este unul dintre cei mai mari producatori auto privati din China, fondat in 1986. Compania mama detine de asemenea Volvo Cars, Polestar si Lotus.',
        foundedYear: 1986,
        isPublished: true,
        sortOrder: 4,
      },
      {
        slug: 'great-wall',
        name: 'Great Wall Motors',
        websiteUrl: 'https://www.gwm.com',
        descriptionEn:
          'Great Wall Motors is China\'s largest SUV and pickup truck manufacturer, founded in 1984. The company operates the ORA electric sub-brand and the premium WEY brand.',
        descriptionRo:
          'Great Wall Motors este cel mai mare producator de SUV-uri si camionete din China, fondat in 1984. Compania opereaza sub-brandul electric ORA si brandul premium WEY.',
        foundedYear: 1984,
        isPublished: true,
        sortOrder: 5,
      },
    ])
    .returning();

  console.log('5 brands created');

  // ─── Models ──────────────────────────────────────────────────────────────

  await db.insert(models).values([
    // BYD models
    {
      brandId: byd.id,
      slug: 'byd-atto-3',
      name: 'ATTO 3',
      propulsion: 'BEV',
      segment: 'suv',
      year: 2024,
      priceEurFrom: 37900,
      priceEurTo: 43900,
      priceUsdFrom: 41000,
      priceUsdTo: 47500,
      batteryKwh: '60.5',
      rangeWltpKm: 420,
      powerKw: 150,
      powerHp: 204,
      torqueNm: 310,
      topSpeedKmh: 160,
      acceleration0100: '7.3',
      lengthMm: 4455,
      widthMm: 1875,
      heightMm: 1615,
      wheelbaseMm: 2720,
      trunkLiters: 440,
      seats: 5,
      driveType: 'FWD',
      chargeTimeDcMin: 29,
      chargePowerDcKw: '88.0',
      chargePowerAcKw: '7.0',
      ncapStars: 5,
      euHomologated: true,
      serviceEurope: true,
      warrantyYears: 6,
      warrantyKm: 150000,
      descriptionEn: 'The BYD ATTO 3 is a compact electric SUV combining Blade Battery safety with a spacious, tech-rich interior at a competitive price point.',
      descriptionRo: 'BYD ATTO 3 este un SUV electric compact care combina siguranta Blade Battery cu un interior spatios si bogat in tehnologie la un pret competitiv.',
      highlightsEn: ['Blade Battery technology', 'NFC key card', 'Rotating 12.8" touchscreen', '5-star Euro NCAP'],
      highlightsRo: ['Tehnologie Blade Battery', 'Card cheie NFC', 'Ecran tactil rotativ 12.8"', '5 stele Euro NCAP'],
      markets: ['DE', 'FR', 'NL', 'SE', 'NO', 'RO'],
      isPublished: true,
      isFeatured: true,
      sortOrder: 1,
    },
    {
      brandId: byd.id,
      slug: 'byd-seal',
      name: 'Seal',
      propulsion: 'BEV',
      segment: 'sedan',
      year: 2024,
      priceEurFrom: 44900,
      priceEurTo: 52900,
      priceUsdFrom: 48500,
      priceUsdTo: 57200,
      batteryKwh: '82.5',
      rangeWltpKm: 570,
      powerKw: 230,
      powerHp: 313,
      torqueNm: 360,
      topSpeedKmh: 180,
      acceleration0100: '5.9',
      lengthMm: 4800,
      widthMm: 1875,
      heightMm: 1460,
      wheelbaseMm: 2920,
      trunkLiters: 400,
      seats: 5,
      driveType: 'RWD',
      chargeTimeDcMin: 26,
      chargePowerDcKw: '150.0',
      chargePowerAcKw: '11.0',
      ncapStars: 5,
      euHomologated: true,
      serviceEurope: true,
      warrantyYears: 6,
      warrantyKm: 150000,
      descriptionEn: 'The BYD Seal is a sleek electric sedan built on the e-Platform 3.0, offering CTB battery integration, impressive range, and dynamic handling.',
      descriptionRo: 'BYD Seal este un sedan electric elegant construit pe platforma e-Platform 3.0, oferind integrare CTB a bateriei, autonomie impresionanta si manevrabilitate dinamica.',
      highlightsEn: ['Cell-to-Body battery', 'e-Platform 3.0', 'iTAC torque control', 'Heat pump standard'],
      highlightsRo: ['Baterie Cell-to-Body', 'e-Platform 3.0', 'Control cuplu iTAC', 'Pompa de caldura standard'],
      markets: ['DE', 'FR', 'NL', 'SE', 'NO'],
      isPublished: true,
      isFeatured: true,
      sortOrder: 2,
    },
    {
      brandId: byd.id,
      slug: 'byd-tang',
      name: 'Tang',
      propulsion: 'BEV',
      segment: 'suv',
      year: 2024,
      priceEurFrom: 69900,
      priceEurTo: 72900,
      priceUsdFrom: 75500,
      priceUsdTo: 78800,
      batteryKwh: '108.8',
      rangeWltpKm: 530,
      powerKw: 380,
      powerHp: 517,
      torqueNm: 700,
      topSpeedKmh: 190,
      acceleration0100: '4.6',
      lengthMm: 4970,
      widthMm: 1955,
      heightMm: 1745,
      wheelbaseMm: 2820,
      trunkLiters: 235,
      seats: 7,
      driveType: 'AWD',
      chargeTimeDcMin: 30,
      chargePowerDcKw: '170.0',
      chargePowerAcKw: '11.0',
      ncapStars: 5,
      euHomologated: true,
      serviceEurope: true,
      warrantyYears: 6,
      warrantyKm: 150000,
      descriptionEn: 'The BYD Tang is a full-size 7-seat electric SUV with dual motors, delivering flagship performance and long-range capability.',
      descriptionRo: 'BYD Tang este un SUV electric cu 7 locuri si motoare duale, oferind performanta de varf si autonomie extinsa.',
      highlightsEn: ['7-seat configuration', 'Dual motor AWD', '108.8 kWh battery', 'DiSus-C suspension'],
      highlightsRo: ['Configuratie 7 locuri', 'AWD cu motor dublu', 'Baterie 108.8 kWh', 'Suspensie DiSus-C'],
      markets: ['DE', 'NL', 'NO', 'SE'],
      isPublished: true,
      sortOrder: 3,
    },

    // NIO models
    {
      brandId: nio.id,
      slug: 'nio-et7',
      name: 'ET7',
      propulsion: 'BEV',
      segment: 'sedan',
      year: 2024,
      priceEurFrom: 69900,
      priceEurTo: 81900,
      priceUsdFrom: 75500,
      priceUsdTo: 88500,
      batteryKwh: '100.0',
      rangeWltpKm: 580,
      powerKw: 480,
      powerHp: 653,
      torqueNm: 850,
      topSpeedKmh: 200,
      acceleration0100: '3.8',
      lengthMm: 5101,
      widthMm: 1987,
      heightMm: 1509,
      wheelbaseMm: 3060,
      trunkLiters: 363,
      seats: 5,
      driveType: 'AWD',
      chargeTimeDcMin: 30,
      chargePowerDcKw: '180.0',
      chargePowerAcKw: '11.0',
      ncapStars: 5,
      euHomologated: true,
      serviceEurope: true,
      warrantyYears: 5,
      warrantyKm: 100000,
      descriptionEn: 'The NIO ET7 is a premium electric sedan featuring an Aquila super-sensing system with LiDAR and battery-swap capability for ultimate convenience.',
      descriptionRo: 'NIO ET7 este un sedan electric premium dotat cu sistemul Aquila de super-detectie cu LiDAR si capacitate de schimb de baterie pentru confort maxim.',
      highlightsEn: ['Battery swap technology', 'Aquila LiDAR system', '150 kWh battery option', 'NOMI AI assistant'],
      highlightsRo: ['Tehnologie de schimb baterie', 'Sistem Aquila LiDAR', 'Optiune baterie 150 kWh', 'Asistent AI NOMI'],
      markets: ['DE', 'NL', 'NO', 'SE', 'DK'],
      isPublished: true,
      isFeatured: true,
      sortOrder: 1,
    },
    {
      brandId: nio.id,
      slug: 'nio-el6',
      name: 'EL6',
      propulsion: 'BEV',
      segment: 'suv',
      year: 2024,
      priceEurFrom: 52900,
      priceEurTo: 62900,
      priceUsdFrom: 57200,
      priceUsdTo: 68000,
      batteryKwh: '75.0',
      rangeWltpKm: 391,
      powerKw: 360,
      powerHp: 490,
      torqueNm: 700,
      topSpeedKmh: 200,
      acceleration0100: '4.5',
      lengthMm: 4854,
      widthMm: 1995,
      heightMm: 1703,
      wheelbaseMm: 2915,
      trunkLiters: 579,
      seats: 5,
      driveType: 'AWD',
      chargeTimeDcMin: 24,
      chargePowerDcKw: '140.0',
      chargePowerAcKw: '11.0',
      euHomologated: true,
      serviceEurope: true,
      warrantyYears: 5,
      warrantyKm: 100000,
      descriptionEn: 'The NIO EL6 is a mid-size electric SUV with battery-swap support, combining sporty performance with everyday practicality.',
      descriptionRo: 'NIO EL6 este un SUV electric de dimensiune medie cu suport pentru schimb de baterie, combinand performanta sportiva cu practicabilitatea zilnica.',
      highlightsEn: ['Battery swap compatible', 'Dual motor AWD', 'Air suspension', 'PanoCinema AR/VR'],
      highlightsRo: ['Compatibil schimb baterie', 'AWD cu motor dublu', 'Suspensie pneumatica', 'PanoCinema AR/VR'],
      markets: ['DE', 'NL', 'NO', 'SE'],
      isPublished: true,
      sortOrder: 2,
    },

    // XPeng models
    {
      brandId: xpeng.id,
      slug: 'xpeng-g6',
      name: 'G6',
      propulsion: 'BEV',
      segment: 'suv',
      year: 2024,
      priceEurFrom: 42500,
      priceEurTo: 51000,
      priceUsdFrom: 46000,
      priceUsdTo: 55100,
      batteryKwh: '87.5',
      rangeWltpKm: 570,
      powerKw: 190,
      powerHp: 258,
      torqueNm: 440,
      topSpeedKmh: 202,
      acceleration0100: '5.9',
      lengthMm: 4753,
      widthMm: 1920,
      heightMm: 1650,
      wheelbaseMm: 2890,
      trunkLiters: 571,
      seats: 5,
      driveType: 'RWD',
      chargeTimeDcMin: 20,
      chargePowerDcKw: '280.0',
      chargePowerAcKw: '11.0',
      euHomologated: true,
      serviceEurope: true,
      warrantyYears: 5,
      warrantyKm: 120000,
      descriptionEn: 'The XPeng G6 is a smart coupe SUV featuring 800V architecture for ultra-fast charging and the advanced XNGP autonomous driving system.',
      descriptionRo: 'XPeng G6 este un SUV coupe inteligent cu arhitectura 800V pentru incarcare ultra-rapida si sistemul avansat de conducere autonoma XNGP.',
      highlightsEn: ['800V architecture', '280 kW DC fast charging', 'XNGP smart driving', '10-25 min fast charge'],
      highlightsRo: ['Arhitectura 800V', 'Incarcare rapida DC 280 kW', 'Conducere inteligenta XNGP', 'Incarcare rapida 10-25 min'],
      markets: ['DE', 'NL', 'NO', 'SE', 'DK'],
      isPublished: true,
      isFeatured: true,
      sortOrder: 1,
    },
    {
      brandId: xpeng.id,
      slug: 'xpeng-p7',
      name: 'P7',
      propulsion: 'BEV',
      segment: 'sedan',
      year: 2024,
      priceEurFrom: 49900,
      priceEurTo: 57900,
      priceUsdFrom: 54000,
      priceUsdTo: 62600,
      batteryKwh: '86.2',
      rangeWltpKm: 505,
      powerKw: 203,
      powerHp: 276,
      torqueNm: 440,
      topSpeedKmh: 200,
      acceleration0100: '6.7',
      lengthMm: 4888,
      widthMm: 1896,
      heightMm: 1450,
      wheelbaseMm: 2998,
      trunkLiters: 450,
      seats: 5,
      driveType: 'RWD',
      chargeTimeDcMin: 29,
      chargePowerDcKw: '175.0',
      chargePowerAcKw: '11.0',
      euHomologated: true,
      serviceEurope: true,
      warrantyYears: 5,
      warrantyKm: 120000,
      descriptionEn: 'The XPeng P7 is a premium electric sedan with sleek coupe styling, long range, and advanced XPILOT autonomous driving technology.',
      descriptionRo: 'XPeng P7 este un sedan electric premium cu design coupe elegant, autonomie mare si tehnologie avansata de conducere autonoma XPILOT.',
      highlightsEn: ['XPILOT 3.5 ADAS', 'Coupe styling', 'Xmart OS 4.0', 'Over-the-air updates'],
      highlightsRo: ['XPILOT 3.5 ADAS', 'Design coupe', 'Xmart OS 4.0', 'Actualizari over-the-air'],
      markets: ['NO', 'SE', 'DK', 'NL'],
      isPublished: true,
      sortOrder: 2,
    },

    // Geely models
    {
      brandId: geely.id,
      slug: 'geely-ex5',
      name: 'Galaxy EX5',
      propulsion: 'BEV',
      segment: 'suv',
      year: 2025,
      priceEurFrom: 33900,
      priceEurTo: 39900,
      priceUsdFrom: 36700,
      priceUsdTo: 43100,
      batteryKwh: '60.0',
      rangeWltpKm: 440,
      powerKw: 160,
      powerHp: 218,
      torqueNm: 320,
      topSpeedKmh: 170,
      acceleration0100: '7.5',
      lengthMm: 4615,
      widthMm: 1901,
      heightMm: 1670,
      wheelbaseMm: 2750,
      trunkLiters: 490,
      seats: 5,
      driveType: 'FWD',
      chargeTimeDcMin: 30,
      chargePowerDcKw: '100.0',
      chargePowerAcKw: '11.0',
      euHomologated: false,
      serviceEurope: false,
      warrantyYears: 5,
      warrantyKm: 100000,
      descriptionEn: 'The Geely Galaxy EX5 is a well-equipped compact electric SUV positioned as a strong value proposition in the European market.',
      descriptionRo: 'Geely Galaxy EX5 este un SUV electric compact bine echipat, pozitionat ca o propunere de valoare puternica pe piata europeana.',
      highlightsEn: ['SEA architecture', 'Competitive pricing', 'Volvo-derived safety', '5-year warranty'],
      highlightsRo: ['Arhitectura SEA', 'Preturi competitive', 'Siguranta derivata Volvo', 'Garantie 5 ani'],
      markets: ['DE', 'FR', 'NL'],
      isPublished: true,
      sortOrder: 1,
    },
    {
      brandId: geely.id,
      slug: 'geely-galaxy-e8',
      name: 'Galaxy E8',
      propulsion: 'BEV',
      segment: 'sedan',
      year: 2025,
      priceEurFrom: 42900,
      priceEurTo: 49900,
      priceUsdFrom: 46400,
      priceUsdTo: 54000,
      batteryKwh: '77.6',
      rangeWltpKm: 510,
      powerKw: 200,
      powerHp: 272,
      torqueNm: 350,
      topSpeedKmh: 190,
      acceleration0100: '6.1',
      lengthMm: 4920,
      widthMm: 1900,
      heightMm: 1465,
      wheelbaseMm: 2928,
      trunkLiters: 420,
      seats: 5,
      driveType: 'RWD',
      chargeTimeDcMin: 25,
      chargePowerDcKw: '200.0',
      chargePowerAcKw: '11.0',
      euHomologated: false,
      serviceEurope: false,
      warrantyYears: 5,
      warrantyKm: 100000,
      descriptionEn: 'The Geely Galaxy E8 is a large electric sedan featuring a stunning 45-inch 8K display and Flyme Auto intelligent cockpit system.',
      descriptionRo: 'Geely Galaxy E8 este un sedan electric mare dotat cu un ecran uimitor de 45 inch 8K si sistemul inteligent de cockpit Flyme Auto.',
      highlightsEn: ['45-inch 8K display', 'Flyme Auto cockpit', 'SEA architecture', '800V fast charging'],
      highlightsRo: ['Ecran 8K de 45 inch', 'Cockpit Flyme Auto', 'Arhitectura SEA', 'Incarcare rapida 800V'],
      markets: ['DE', 'NL'],
      isPublished: true,
      sortOrder: 2,
    },

    // Great Wall models
    {
      brandId: greatWall.id,
      slug: 'ora-funky-cat',
      name: 'ORA Funky Cat',
      propulsion: 'BEV',
      segment: 'hatchback',
      year: 2024,
      priceEurFrom: 35900,
      priceEurTo: 40900,
      priceUsdFrom: 38800,
      priceUsdTo: 44200,
      batteryKwh: '63.0',
      rangeWltpKm: 420,
      powerKw: 126,
      powerHp: 171,
      torqueNm: 250,
      topSpeedKmh: 160,
      acceleration0100: '8.3',
      lengthMm: 4235,
      widthMm: 1825,
      heightMm: 1596,
      wheelbaseMm: 2650,
      trunkLiters: 228,
      seats: 5,
      driveType: 'FWD',
      chargeTimeDcMin: 43,
      chargePowerDcKw: '64.0',
      chargePowerAcKw: '6.6',
      ncapStars: 5,
      euHomologated: true,
      serviceEurope: true,
      warrantyYears: 5,
      warrantyKm: 100000,
      descriptionEn: 'The ORA Funky Cat is a retro-styled compact electric hatchback combining charming design with 5-star Euro NCAP safety and practical daily usability.',
      descriptionRo: 'ORA Funky Cat este un hatchback electric compact cu stil retro, combinand un design fermecator cu siguranta Euro NCAP de 5 stele si utilizabilitate practica zilnica.',
      highlightsEn: ['Retro-modern design', '5-star Euro NCAP', 'Affordable EV', 'Coffee-inspired interior'],
      highlightsRo: ['Design retro-modern', '5 stele Euro NCAP', 'EV accesibil', 'Interior inspirat de cafea'],
      markets: ['DE', 'UK', 'IL', 'SE'],
      isPublished: true,
      isFeatured: true,
      sortOrder: 1,
    },
    {
      brandId: greatWall.id,
      slug: 'wey-coffee-01',
      name: 'WEY Coffee 01',
      propulsion: 'PHEV',
      segment: 'suv',
      year: 2024,
      priceEurFrom: 55900,
      priceEurTo: 59900,
      priceUsdFrom: 60500,
      priceUsdTo: 64800,
      batteryKwh: '39.7',
      rangeWltpKm: 146,
      powerKw: 350,
      powerHp: 476,
      torqueNm: 847,
      topSpeedKmh: 235,
      acceleration0100: '4.9',
      lengthMm: 4871,
      widthMm: 1960,
      heightMm: 1690,
      wheelbaseMm: 2915,
      trunkLiters: 350,
      seats: 5,
      driveType: 'AWD',
      chargeTimeDcMin: 45,
      chargePowerDcKw: '60.0',
      chargePowerAcKw: '7.4',
      ncapStars: 5,
      euHomologated: true,
      serviceEurope: true,
      warrantyYears: 5,
      warrantyKm: 100000,
      descriptionEn: 'The WEY Coffee 01 is a premium plug-in hybrid SUV from Great Wall\'s luxury brand, offering combined electric and petrol range with high-end features.',
      descriptionRo: 'WEY Coffee 01 este un SUV plug-in hybrid premium de la brandul de lux Great Wall, oferind autonomie combinata electrica si pe benzina cu dotari de top.',
      highlightsEn: ['Premium PHEV SUV', '146 km electric range', 'AWD dual motor', '5-star Euro NCAP'],
      highlightsRo: ['SUV PHEV premium', '146 km autonomie electrica', 'AWD motor dublu', '5 stele Euro NCAP'],
      markets: ['DE'],
      isPublished: true,
      sortOrder: 2,
    },
  ]);

  console.log('Sample models created');

  console.log('Seeding complete!');
  process.exit(0);
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
